name: palestine_first_run
description: Lightweight and easy check if the app runs for its first time, apply that to custom calls.
version: 0.0.8

homepage: https://github.com/msayed-net/PalestineDevelopers

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  shared_preferences: ^2.0.11

dev_dependencies:
  lint: ^1.8.1
  test: ^1.20.1

flutter:
  plugin:
    platforms:
      android:
        package: com.example.palestine_first_run
        pluginClass: PalestineFirstRunPlugin
      ios:
        pluginClass: PalestineFirstRunPlugin
      web:
        pluginClass: PalestineFirstRunWeb
        fileName: palestine_first_run_web.dart
