name: palestine_first_run
description: Lightweight and easy check if the app runs for its first time, apply that to custom calls.
version: 0.0.10
homepage: https://github.com/msayed-net/PalestineDevelopers

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.7

dev_dependencies:
  lint: ^1.5.2
  test: ^1.20.1
